"""empty message

Revision ID: 91fe9fad3e7e
Revises: 
Create Date: 2024-05-04 14:15:46.863656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91fe9fad3e7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('specialization', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_doctors_username'), ['username'], unique=True)

    op.create_table('patient_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('patient_id', sa.String(length=32), nullable=True),
    sa.Column('age', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_info_patient_id'), ['patient_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_patient_info_username'), ['username'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('brain_img', sa.String(length=64), nullable=False),
    sa.Column('classifier', sa.String(length=32), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_info.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=False),
    sa.Column('doctor_name', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_history')
    op.drop_table('patients')
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_info_username'))
        batch_op.drop_index(batch_op.f('ix_patient_info_patient_id'))

    op.drop_table('patient_info')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_username'))
        batch_op.drop_index(batch_op.f('ix_doctors_email'))

    op.drop_table('doctors')
    # ### end Alembic commands ###
